name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: "Publish QGIS release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download release
        uses: i3h/download-release-asset@v1
        with:
          owner: olsen232
          repo: kart-qgis-plugin
          tag: ${{ github.ref_name }}
          file: "kart-${{ github.ref_name }}.zip"

      - name: Publish to QGIS
        env:
          QGIS_CREDENTIALS: ${{ secrets.QGIS_CREDENTIALS }}
        run: |
          ls -l ./helper.py
          ls -l "kart-${{ github.ref_name }}.zip"
