name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: "Publish QGIS release"
    runs-on: ubuntu-latest

    steps:
      - name: Experiment with echo
        run: |
          echo "env.GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
          echo "env.GITHUB_REF: ${{ env.GITHUB_REF }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref: ${{ github.ref }}"

      - name: Experiment with ls
        run: |
          pwd
          ls ../..
          tree ../..

      - name: Download release
        uses: i3h/download-release-asset@v1
        with:
          owner: olsen232
          repo: kart-qgis-plugin
          tag: ${{ env.GITHUB_REF_NAME }}
          file: "kart-${{ env.GITHUB_REF_NAME }}.zip"

